# Copy this file to .copado-hx.ini at the root of your Salesforce DX project.

[project]
source_dir = force-app
mdapi_dir = mdapi
manifest = manifest/package.xml

[salesforce]
target_org = devhub-or-sandbox-alias
test_level = RunLocalTests
wait_minutes = 60

[copado]
username = copado-admin@example.com
user_story = US-000001
base_branch = main

[git]
remote = origin
